# Generated by Django 4.2.11 on 2024-09-21 07:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon_class', models.CharField(default='fa-regular fa-sparkles', help_text="Font Awesome icon class, e.g., 'fa-calculator-simple'", max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EduCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '911234567'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('logo', models.ImageField(upload_to='logos/')),
                ('verify', models.BooleanField(default=False)),
                ('partner', models.BooleanField(default=False)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('instagram_link', models.CharField(blank=True, max_length=300)),
                ('telegram_link', models.CharField(blank=True, max_length=300)),
                ('facebook_link', models.CharField(blank=True, max_length=300)),
                ('categories', models.ManyToManyField(blank=True, related_name='edu_centers', to='main.category')),
                ('edu_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.educationtype')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('now_place', models.IntegerField()),
                ('current_place', models.IntegerField()),
                ('teacher', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('intensive', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('days', models.ManyToManyField(to='main.day')),
                ('edu_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main.educenter')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.level')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='levels',
            field=models.ManyToManyField(to='main.level'),
        ),
        migrations.AddField(
            model_name='branch',
            name='edu_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.educenter'),
        ),
    ]
