# Generated by Django 4.2.11 on 2024-09-21 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('banner', models.ImageField(upload_to='events')),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField(blank=True)),
                ('link', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('edu_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.educenter')),
            ],
        ),
    ]
