# Generated by Django 4.2.11 on 2024-09-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='levels',
        ),
    ]
